import type { Entity } from '../../types';
import type { WikiEditStartAnchor } from './WikiEditorPane';

/** Params for useWikiSync (subset of WikiPersistenceParams) */
export type WikiSyncParams = {
  canEditPage: boolean;
  setMode: React.Dispatch<React.SetStateAction<'edit' | 'read'>>;
  selectedPageId: string | null;
  projectId: string;
  pages: Entity[];
  docById: Record<string, string | undefined>;
  titleById: Record<string, string>;
  setDocById: React.Dispatch<React.SetStateAction<Record<string, string | undefined>>>;
  setLastSavedDocById: React.Dispatch<React.SetStateAction<Record<string, string | undefined>>>;
  setTitleById: React.Dispatch<React.SetStateAction<Record<string, string>>>;
  setLastSavedTitleById: React.Dispatch<React.SetStateAction<Record<string, string | undefined>>>;
  setCrdtBlobById: React.Dispatch<React.SetStateAction<Record<string, number[] | undefined>>>;
  setLoadingDocId: React.Dispatch<React.SetStateAction<string | null>>;
  docByIdRef: React.MutableRefObject<Record<string, string | undefined>>;
  lastSavedDocByIdRef: React.MutableRefObject<Record<string, string | undefined>>;
  titleByIdRef: React.MutableRefObject<Record<string, string>>;
  lastSavedTitleByIdRef: React.MutableRefObject<Record<string, string | undefined>>;
  lastSyncedUpdatedAtByIdRef: React.MutableRefObject<Record<string, number>>;
  pagesRef: React.MutableRefObject<Entity[]>;
  projectIdRef: React.MutableRefObject<string>;
  listSyncInFlightRef: React.MutableRefObject<boolean>;
  pageSyncInFlightRef: React.MutableRefObject<boolean>;
  onRefreshProjectRef: React.MutableRefObject<(() => void | Promise<unknown>) | undefined>;
  selectedPageIdRef: React.MutableRefObject<string | null>;
  autoEditPageIdRef: React.MutableRefObject<string | null>;
  commentValuesRef: React.MutableRefObject<Record<string, any>>;
  commentValuesPageIdRef: React.MutableRefObject<string | null>;
  editingCommentIdRef: React.MutableRefObject<string | null>;
  commentDirtyByIdRef: React.MutableRefObject<Record<string, boolean>>;
  newCommentDraftRef: React.MutableRefObject<{ hasDraft: boolean }>;
  setCommentValues: React.Dispatch<React.SetStateAction<Record<string, any>>>;
  includeDocSaves: boolean;
  setEditorResetTokenById: React.Dispatch<React.SetStateAction<Record<string, number>>>;
};

export type WikiPersistenceParams = {
  canEditPage: boolean;
  mode: 'edit' | 'read';
  setMode: React.Dispatch<React.SetStateAction<'edit' | 'read'>>;
  selectedPageId: string | null;
  projectId: string;
  pages: Entity[];
  selected: Entity | null;
  sortedPages: Entity[];
  onCreatePage: (opts?: { parentId?: string | null; nodeType?: 'page' | 'folder' }) => Entity;
  onDeletePage: (id: string) => void;
  onSelectPage: (id: string) => void;
  onUpdatePage: (id: string, patch: Record<string, any>) => void;
  onUpdatePageRef: React.MutableRefObject<(id: string, patch: Record<string, any>) => void>;
  onRefreshProjectRef: React.MutableRefObject<(() => void | Promise<unknown>) | undefined>;
  saveTick: number;
  setSaveTick: React.Dispatch<React.SetStateAction<number>>;
  includeDocSaves: boolean;
  docById: Record<string, string | undefined>;
  setDocById: React.Dispatch<React.SetStateAction<Record<string, string | undefined>>>;
  setCrdtBlobById: React.Dispatch<React.SetStateAction<Record<string, number[] | undefined>>>;
  docByIdRef: React.MutableRefObject<Record<string, string | undefined>>;
  lastSavedDocById: Record<string, string | undefined>;
  setLastSavedDocById: React.Dispatch<React.SetStateAction<Record<string, string | undefined>>>;
  lastSavedDocByIdRef: React.MutableRefObject<Record<string, string | undefined>>;
  titleById: Record<string, string>;
  setTitleById: React.Dispatch<React.SetStateAction<Record<string, string>>>;
  titleByIdRef: React.MutableRefObject<Record<string, string>>;
  lastSavedTitleById: Record<string, string | undefined>;
  setLastSavedTitleById: React.Dispatch<React.SetStateAction<Record<string, string | undefined>>>;
  lastSavedTitleByIdRef: React.MutableRefObject<Record<string, string | undefined>>;
  setLoadingDocId: React.Dispatch<React.SetStateAction<string | null>>;
  pageListContainerRef: React.MutableRefObject<HTMLDivElement | null>;
  selectedPageIdRef: React.MutableRefObject<string | null>;
  lastCreatedPageIdRef: React.MutableRefObject<string | null>;
  autoEditPageIdRef: React.MutableRefObject<string | null>;
  lastSyncedUpdatedAtByIdRef: React.MutableRefObject<Record<string, number>>;
  pagesRef: React.MutableRefObject<Entity[]>;
  projectIdRef: React.MutableRefObject<string>;
  listSyncInFlightRef: React.MutableRefObject<boolean>;
  pageSyncInFlightRef: React.MutableRefObject<boolean>;
  scrollTopByPageIdRef: React.MutableRefObject<Record<string, number>>;
  setEditorResetTokenById: React.Dispatch<React.SetStateAction<Record<string, number>>>;
  setPendingEditAnchorById: React.Dispatch<React.SetStateAction<Record<string, WikiEditStartAnchor | undefined>>>;
  setEditFocusTokenById: React.Dispatch<React.SetStateAction<Record<string, number>>>;
  commentValuesRef: React.MutableRefObject<Record<string, any>>;
  commentValuesPageIdRef: React.MutableRefObject<string | null>;
  editingCommentIdRef: React.MutableRefObject<string | null>;
  commentDirtyByIdRef: React.MutableRefObject<Record<string, boolean>>;
  newCommentDraftRef: React.MutableRefObject<{ hasDraft: boolean }>;
  setCommentValues: React.Dispatch<React.SetStateAction<Record<string, any>>>;
  dialog: {
    confirm: (opts: { title: string; message: string; confirmText: string; danger?: boolean }) => Promise<boolean>;
    prompt: (opts: {
      title?: string;
      message: string;
      defaultValue?: string;
      placeholder?: string;
      confirmText?: string;
      cancelText?: string;
    }) => Promise<string | null>;
  };
};
